### ISSUE TITLE
Getting exception while scep enrollment from device

### ISSUE THREAD

**Issue by AshiqKony** [jscep/jscep#68]
Hi,

I am trying to connect to scep server to get certificate but getting following exception

org.jscep.client.ClientException: org.jscep.transport.response.InvalidContentTypeException: Expected [application/x-x509-ca-cert, application/x-x509-ca-ra-cert], but was text/html;charset=ISO-8859-1

Can you tell me the reason for this 

Thanks & Regards,
Ashiq Sayyad

**Comment by seize-the-dave** [comment]
Your SCEP server appears to be serving HTML content.  I would consider visiting the endpoint using a web browser first.  This isn't a jscep issue, so I'm closing it.

**Comment by seize-the-dave** [comment]
I believe your SCEP server is serving up HTML.  This isn't a jscep bug.

On 25 Oct 2016 7:15 am, "AshiqKony" <notifications@github.com> wrote:

Hi,

I am trying to connect to scep server to get certificate but getting
following exception

org.jscep.client.ClientException:
org.jscep.transport.response.InvalidContentTypeException:
Expected [application/x-x509-ca-cert, application/x-x509-ca-ra-cert], but
was text/html;charset=ISO-8859-1

Can you tell me the reason for this

Thanks & Regards,
Ashiq Sayyad

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jscep/jscep/issues/68>, or mute the thread
